### PR TITLE
chore: update release-please action

### PR DESCRIPTION
**Pull request by targos**
Hopefully it will work better, see https://github.com/nodejs/gyp-next/pull/167

### CODE REVIEW

**Comment by cclauss** [comment]
I doubt that `version-file: pylib/gyp/__init__.py` will work but worth a try...
* https://github.com/google-github-actions/release-please-action#configuration

**Review by cclauss — APPROVED** [review]

**Comment by targos** [comment]
By looking at https://github.com/googleapis/release-please/blob/dd78a70688747054a755801df69d5ce3a2ca0f07/src/strategies/python.ts#L80-L117
I think the solution is either to create a `pyproject.toml` or set `component: gyp` in the workflow.

**Comment by targos** [comment]
The problem being that the project is called `gyp-next`, but the code is still located in `pylib/gyp`

**Comment by cclauss** [comment]
So, is it:
* [ ] `component: gyp`
* [ ] `component: gyp-next`
* [ ] `component: pylib/gyp`
* [ ] `component: pylib.gyp`
* [ ] `component: pylib-gyp`
* [ ] `component: pylib_gyp`

I will try to convert to `pyproject.toml`

**Comment by gengjiawen** [comment]
If this still not work, we can patch the version automatically,  see https://github.com/gengjiawen/monkey-rust/blob/35485ce9c5f596cd1982a1be53f84a2edbefdd2b/.github/workflows/prepare-release.yml#L12

**Review by ryzokuken — APPROVED** [review]

**Pull request merged**
