### PR TITLE
chore: update Ruff to 0.3.1

### PR DESCRIPTION
**Pull request by targos**
- Fix new UP032 errors
    - Fix deprecated Ruff config structure

### CODE REVIEW

**Review by legendecas — COMMENTED** [review]
Can we pin ruff version as well?

**Comment by legendecas** [comment]
FWIW, I pinned ruff to v0.3.0 in https://github.com/nodejs/gyp-next/pull/223

**Comment by targos** [comment]
Ok, I changed this to a Ruff update.

**Review by legendecas — APPROVED** [review]

**Review by cclauss — APPROVED** [review]

**Comment by cclauss** [comment]
My preference is that we do not pin `ruff` because it is still in a state of flux and fixing Python code incrementally in a JavaScript codebase ensures that the squeaky wheel gets the grease.  If we silence `ruff` then we will build a backlog of diverse changes that will be difficult to implement and get reviewed.

**Pull request merged**
