### PR TITLE
chore (main): vendor in Python packaging for Py3.12

### LINKED ISSUE #211: Python tests broken
https://github.com/nodejs/gyp-next/actions/runs/6560318675/job/17817683531

```
Run ruff --format=github .
  ruff --format=github .
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.8.18/x64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.8.18/x64
    Python[2](https://github.com/nodejs/gyp-next/actions/runs/6560318675/job/17817683531#step:6:2)_ROOT_DIR: /Users/runner/hostedtoolcache/Python/[3](https://github.com/nodejs/gyp-next/actions/runs/6560318675/job/17817683531#step:6:3).8.18/x6[4](https://github.com/nodejs/gyp-next/actions/runs/6560318675/job/17817683531#step:6:4)
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.8.18/x[6](https://github.com/nodejs/gyp-next/actions/runs/6560318675/job/17817683531#step:6:6)4
error: unexpected argument '--format' found

  tip: to pass '--format' as a value, use '-- --format'

Usage: ruff check [OPTIONS] [FILES]...

For more information, try '--help'.
```

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #211
Fixes #213

Related to:
* #211
* #213
* nodejs/node-gyp#2862
* nodejs/node-gyp#2869
* nodejs/node-gyp#2888
* nodejs/node-gyp#2912
* nodejs/node-gyp#2915

`distutils` was removed in Python 3.12 and the Python Packaging Authority recommends using
https://github.com/pypa/packaging (https://pypi.org/project/packaging) instead.

Let's _vendor in_ `packaging` so that installing `node-gyp` does not require running `pip install packaging`.

@rzhao271 @DeeDeeG @StefanStojanovic @brjsp

### CODE REVIEW

**Review by rzhao271 — COMMENTED** [review]
Do we still need line 15 in the TOML file?
The line that says `dependencies = ["packaging>=23.1"]`

**Comment by DeeDeeG** [comment]
I think for open source license compliance, `LICENSE`, `LICENSE.APACHE` and `LICENSE.BSD` from here: https://github.com/pypa/packaging should be included alongside all the vendored `packaging` files.

**Comment by cclauss** [comment]
* [x] `dependencies = ["packaging>=23.1"]` commented out with an added explanation.
* [x] `LICENSE`, `LICENSE.APACHE`, and `LICENSE.BSD` copied into `pylib/packaging`

**Review by targos — APPROVED** [review]
rubberstamp

**Pull request merged**
