### PR TITLE
fix(make): only generate makefile for multiple toolsets if requested

### PR DESCRIPTION
**Pull request by targos**
It's already like this in the msvs and ninja generators.

Refs: https://github.com/nodejs/node/pull/40934

### CODE REVIEW

**Comment by targos** [comment]
Here's the definition of `CrossCompileRequested`: https://github.com/nodejs/gyp-next/blob/45475a7d6ac9b9efdb3414dbb9c9021c48d8acaf/pylib/gyp/common.py#L632-L643

**Comment by targos** [comment]
The windows build failure is probably unrelated but I don't know what could be causing it:

```
gyp: Undefined variable PRODUCT_DIR_ABS in deps\openssl\openssl.gyp while loading dependencies of node.gyp while trying to load node.gyp
```

**Comment by richardlau** [comment]
> The windows build failure is probably unrelated but I don't know what could be causing it:
> 
> ```
> gyp: Undefined variable PRODUCT_DIR_ABS in deps\openssl\openssl.gyp while loading dependencies of node.gyp while trying to load node.gyp
> ```

Wasn't there something about a gyp change for OpenSSL 3 not making it back upstream?

**Comment by richardlau** [comment]
https://github.com/nodejs/node/issues/40735 (raised by yourself 🙂 )

**Comment by targos** [comment]
Right 🤦🏻

**Comment by targos** [comment]
Can I please have some reviews? I'd like to ignore the Node.js integration errors again. We can see in https://github.com/nodejs/node/pull/40934 that the patch doesn't break Windows.

**Review by cclauss — APPROVED** [review]
LGTM

**Review by richardlau — APPROVED** [review]

**Pull request merged**
