### PR TITLE
ci: add workflow to test Node.js POSIX integration

### PR DESCRIPTION
**Pull request by targos**
Build on ubuntu-latest and macOS-latest.

### CODE REVIEW

**Review by gengjiawen — APPROVED** [review]

**Comment by gengjiawen** [comment]
@targos Maybe add windows support too ? Only need to add nasm should work.

**Review by ryzokuken — APPROVED** [review]

**Comment by targos** [comment]
@ryzokuken this PR was not ready :(

**Comment by ryzokuken** [comment]
I'm sorry! I couldn't guess that from the changes or the conversation here and the PR was not set to "draft" mode :sweat_smile: 

Would you prefer to make a quick follow-up or should I revert it?

**Comment by targos** [comment]
We should revert it. The CI was not passing

**Pull request merged**
