### PR TITLE
fix: avoid quoting cflag name and parameter with space separator

### PR DESCRIPTION
**Pull request by legendecas**
Fixes: https://github.com/nodejs/node-gyp/issues/2858

Avoid quoting `-arch arm64` in generated `compile_commands.json` as `c++ "-arch arm64"`.

### CODE REVIEW

**Comment by legendecas** [comment]
@nodejs/gyp I'd appreciate it if this could have a review, thank you!

**Review by cclauss — CHANGES_REQUESTED** [review]
Please consider adding tests that fail without these changes but pass with these changes so that we can avoid future regressions.

**Review by cclauss — APPROVED** [review]
Nice!

Perhaps create a DRAFT PR with only the test changes to prove that the tests fail on the unmodified code

**Comment by legendecas** [comment]
Sure, https://github.com/nodejs/gyp-next/pull/224

**Pull request merged**
