### PR TITLE
test: Run tests on Node.js v22

### PR DESCRIPTION
**Pull request by cclauss**
https://nodejs.org/en/blog/announcements/v22-release-announce

### CODE REVIEW

**Comment by targos** [comment]
Windows CI is broken by https://github.com/nodejs/node/issues/52682

**Comment by targos** [comment]
For actions/setup-python errors, it seems to be https://github.com/actions/setup-python/issues/852

**Comment by cclauss** [comment]
Python issues fixed by explicitly selecting `macos-13` and `macos-14` (X64 Intel vs. ARM64 Apple Silicon).

**Comment by cclauss** [comment]
https://community.chocolatey.org/packages/nodejs

**Comment by cclauss** [comment]
In GitHub Actions:
```yaml
        if: runner.os == 'Windows'
        shell: bash  # Not pwsh 
        run: |
          npm install -g npm  # >= https://github.com/npm/cli/releases/tag/v10.7.0
```

**Comment by legendecas** [comment]
node-gyp integration failures are related to: https://github.com/nodejs/nan/issues/968

**Comment by legendecas** [comment]
The `codecs.charmap_encode` error outputs are noises as it is used to skip tests: https://github.com/nodejs/node-gyp/blob/main/test/test-addon.js#L59

**Comment by cclauss** [comment]
https://github.com/actions/node-versions/releases/tag/22.1.0-8926142033

**Comment by cclauss** [comment]
@legendecas @StefanStojanovic Any idea how we can fix the `UnicodeEncodeError` so we can land this in
* #253

**Comment by legendecas** [comment]
@cclauss the unicode error is unrelevant, see https://github.com/nodejs/gyp-next/pull/244#issuecomment-2090011082. The real error is caused by https://github.com/nodejs/node/pull/52794, which should be released in the next week's new v22 version.

**Comment by StefanStojanovic** [comment]
@cclauss Node.js v22.2 was released, would it make sense to resolve conflicts and try this now without the Windows exclude?

**Review by StefanStojanovic — APPROVED** [review]
LGTM since the checks are green.

**Pull request merged**
