### PR TITLE
Apply autopep8 formatter

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by cclauss** [comment]
Lots of conflicts.  I would much prefer the Python Software Foundation's "black" formatter because is it not configurable (a feature!) like Standard and GoFmt.

**Comment by targos** [comment]
Rebased.

**Comment by targos** [comment]
I only added the max line length option, which also exists with the black formatter. Would the output be much different with it? I personally don't really care.

**Comment by cclauss** [comment]
Let’s shift to `black` and not configure max_line_length.  It will default to max 88 chars per line for the reasons discussed in the black readme.  My sense is that the PSF is trying to establish to conical Python format and we should go with that flow.

**Comment by targos** [comment]
Alternative: https://github.com/nodejs/gyp-next/pull/17

**Comment by ryzokuken** [comment]
Closing this in favor of #17

**Pull request closed without merging**
