### PR TITLE
chore(release): v0.4.0

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by ryzokuken** [comment]
@targos will you push the tag manually? I could push this version to pip then.

**Comment by cclauss** [comment]
Our README says nothing about this code being available on PyPI.

**Comment by targos** [comment]
I push the tag

**Comment by ryzokuken** [comment]
Released! https://pypi.org/project/gyp-next/0.4.0/

Thanks @cclauss for updating the README.

**Pull request merged**
