### PR TITLE
(xcode) feat: --cross-compiling overrides arch-specific settings

### PR DESCRIPTION
**Pull request by rvagg**
Continuing from https://github.com/nodejs/build/issues/2474#issuecomment-727880495

GYP_CROSSCOMPILE isn't used in the Xcode path at all, so this shouldn't conflict with anything afaik. This feels like a bit of a hack but elegance is beyond me for this. The problem we have is that `-arch X` is provided to all compile commands via `CFLAGS_Release` and friends, regardless of host or target, and you can't override it by any other means, even if you can sneak in extra args via `CC.target`, `CC.host` and friends.

I think this wouldn't be a problem if we didn't need the built-time tooling to be runnable on the host arch. So even though there's logic in there for "iphone" etc., those assume a single compile target, not the intermediate host compile for build-time tooling. I _think_. But maybe you folks can have a bit of a look to see if there's a more elegant way or something I'm overlooking here?

### CODE REVIEW

**Comment by rvagg** [comment]
(view whitespace changes off btw https://github.com/nodejs/gyp-next/pull/78/files?diff=unified&w=1)

**Comment by bcoe** [comment]
@rvagg sorry for being a pendant, but for the parser to pick up this change for a release, you'll want to go with:

```
feat(xcode) : --cross-compiling overrides arch-specific settings
```

When you land 👍

**Comment by rvagg** [comment]
pointer appreciated, have amended and force pushed, thanks @bcoe

**Review by gengjiawen — APPROVED** [review]
LGTM

**Comment by gengjiawen** [comment]
cc @MarshallOfSound @targos

**Review by ryzokuken — APPROVED** [review]

**Comment by MarshallOfSound** [comment]
Can we validate this doesn't break existing X-compilatiom of native add-ons as that currently works.  If no one gets to it I can test it later this week.  Also unclear to me how X-compilation of native add-ons works but doesn't for node itself, they both use the same gyp-next toolchain right?

**Comment by gengjiawen** [comment]
> Can we validate this doesn't break existing X-compilatiom of native add-ons as that currently works. If no one gets to it I can test it later this week. 

This will be great.

> Also unclear to me how X-compilation of native add-ons works but doesn't for node itself, they both use the same gyp-next toolchain right?

Yeap. But gyp-next in node only responsible for build Node.js itself.

**Comment by rvagg** [comment]
> Can we validate this doesn't break existing X-compilatiom of native add-ons as that currently works

For cross compiling on macos? Or in general? Currently the only cross that should be supported on macos (using the xcode path) is i386. But if you're successfully cross compiling anything else on macos then that'd be interesting to hear about! Perhaps I've missed something.

**Comment by gengjiawen** [comment]
@MarshallOfSound ping.

**Comment by gengjiawen** [comment]
@MarshallOfSound friendly ping again.

**Comment by MarshallOfSound** [comment]
Ah sorry folks, this got drowned out in my other GH notifications.

> For cross compiling on macos? Or in general? Currently the only cross that should be supported on macos (using the xcode path) is i386. But if you're successfully cross compiling anything else on macos then that'd be interesting to hear about! Perhaps I've missed something.

We X-compile arm64 from x64 at the moment using the xcode path.

Gave this a quick test and it doesn't look like it messes with that so LGTM 👍

**Comment by gengjiawen** [comment]
> Ah sorry folks, this got drowned out in my other GH notifications.
> 
> > For cross compiling on macos? Or in general? Currently the only cross that should be supported on macos (using the xcode path) is i386. But if you're successfully cross compiling anything else on macos then that'd be interesting to hear about! Perhaps I've missed something.
> 
> We X-compile arm64 from x64 at the moment using the xcode path.
> 
> Gave this a quick test going both arm64 from x64 and arm64 via Rosetta on an M1 and it doesn't look like it messes with that so LGTM 👍

Thanks for the test :)

**Pull request merged**
