### PR TITLE
build: support apple silicon (arm64 darwin) builds

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Pairs with https://github.com/nodejs/node-gyp/pull/2165

### CODE REVIEW

**Comment by cclauss** [comment]
We will have to monitor https://blog.macstadium.com/category/macstadium-news to see when the new Apple hardware is added.

**Comment by MarshallOfSound** [comment]
You can test the "build" part using any machine with the Xcode 12.0 UA preview on it, but you won't be able to ensure it actually runs / works without an apple-silicon machine somewhere.  Definitely works on my DTK though 😄

**Comment by ryzokuken** [comment]
@MarshallOfSound great. I'll merge this in after another review and once that's done I suppose we could make a minor release with this. Would you mind adding this to the changelog file?

**Comment by MarshallOfSound** [comment]
@ryzokuken Updated

**Pull request merged**
