### PR TITLE
chore: add .gitignore

### PR DESCRIPTION
**Pull request by targos**
Copied from https://github.com/github/gitignore/blob/master/Python.gitignore

### CODE REVIEW

**Comment by targos** [comment]
@ryzokuken no. We need to set specific guidelines for this repo.

**Comment by ryzokuken** [comment]
Either way, I'm merging this since it's unlikely to attract criticism.

**Comment by ryzokuken** [comment]
Eh, for some reason I can't merge it?

**Comment by targos** [comment]
It doesn't say the reason?

**Comment by BridgeAR** [comment]
"Required statuses must pass before merging"

**Comment by targos** [comment]
It looks like the github action didn't run. I removed the requirement for now.

**Pull request merged**
