### PR TITLE
GitHub Actions: Test Python 3.9 release candidate 1

### PR DESCRIPTION
**Pull request by cclauss**
https://www.python.org/download/pre-releases/

### CODE REVIEW

**Review by ryzokuken — APPROVED** [review]
LGTM, thanks.

**Comment by ryzokuken** [comment]
That said, idk what others think about testing on pre-release versions. @targos @gengjiawen @mmarchini wdyt?

**Comment by cclauss** [comment]
This is a release candidate and GA is in 3 weeks.

**Review by mmarchini — APPROVED** [review]
sgtm

**Review by richardlau — COMMENTED** [review]
Checks are passing so +1 to adding. We should switch over to the proper release once it GA's.

**Review by richardlau — APPROVED** [review]

**Comment by ryzokuken** [comment]
Thanks everyone.

**Pull request merged**
